[project]
name = "where-buy-property"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "fastapi>=0.119.1",
    "geopy>=2.4.1",
    "playwright>=1.55.0",
    "requests>=2.32.5",
    "ruff>=0.14.1",
]
